presets:
  lightning_d405_d455_no_tactile:
    label: "Lightning + D405 + D455"
    active_arms: "lightning"
    dataset_id: "spark_multisensor_lightning_v1"
    robot_id: "spark_lightning"
    task_name: "pick_place"
    language_instruction: "pick up the object and place it in the target area"
    operator: ""
    sensors_file: "data_pipeline/configs/sensors.local.yaml"
    session_devices:
      - kind: realsense
        identifier: "130322273305"
        serial_number: "130322273305"
        enabled: true
        suggested_role: "lightning_wrist_1"
        resolved_role: "lightning_wrist_1"
      - kind: realsense
        identifier: "213622251272"
        serial_number: "213622251272"
        enabled: true
        suggested_role: "scene_1"
        resolved_role: "scene_1"
    viewer_base_url: "http://10.33.55.65:3000"

  lightning_d405_d455_left_gelsight:
    label: "Lightning + D405 + D455 + Left GelSight"
    active_arms: "lightning"
    dataset_id: "spark_multisensor_lightning_tactile_v1"
    robot_id: "spark_lightning"
    task_name: "pick_place"
    language_instruction: "pick up the object and place it in the target area"
    operator: ""
    sensors_file: "data_pipeline/configs/sensors.local.yaml"
    session_devices:
      - kind: realsense
        identifier: "130322273305"
        serial_number: "130322273305"
        enabled: true
        suggested_role: "lightning_wrist_1"
        resolved_role: "lightning_wrist_1"
      - kind: realsense
        identifier: "213622251272"
        serial_number: "213622251272"
        enabled: true
        suggested_role: "scene_1"
        resolved_role: "scene_1"
      - kind: gelsight
        identifier: "/dev/v4l/by-id/usb-Arducam_Technology_Co.__Ltd._GelSight_Mini_R0B_28D8-PXEC_28D8PXEC-video-index0"
        device_path: "/dev/v4l/by-id/usb-Arducam_Technology_Co.__Ltd._GelSight_Mini_R0B_28D8-PXEC_28D8PXEC-video-index0"
        enabled: true
        suggested_role: "lightning_finger_left"
        resolved_role: "lightning_finger_left"
    viewer_base_url: "http://10.33.55.65:3000"

  lightning_d405_l515_no_tactile:
    label: "Lightning + D405 + L515"
    active_arms: "lightning"
    dataset_id: "spark_multisensor_lightning_v1"
    robot_id: "spark_lightning"
    task_name: "pick_place"
    language_instruction: "pick up the object and place it in the target area"
    operator: ""
    sensors_file: "data_pipeline/configs/sensors.local.yaml"
    session_devices:
      - kind: realsense
        identifier: "130322273305"
        serial_number: "130322273305"
        enabled: true
        suggested_role: "lightning_wrist_1"
        resolved_role: "lightning_wrist_1"
      - kind: realsense
        identifier: "f1380660"
        serial_number: "f1380660"
        enabled: true
        suggested_role: "scene_2"
        resolved_role: "scene_2"
    viewer_base_url: "http://10.33.55.65:3000"
